# Generated by Django 5.1.4 on 2024-12-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
